# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ds.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1296, 1080)
        self.frame1_4 = QtWidgets.QFrame(Dialog)
        self.frame1_4.setGeometry(QtCore.QRect(30, 30, 1200, 1000))
        self.frame1_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame1_4.setObjectName("frame1_4")
        self.label_4 = QtWidgets.QLabel(self.frame1_4)
        self.label_4.setGeometry(QtCore.QRect(290, 40, 241, 41))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btn_confirm = QtWidgets.QPushButton(self.frame1_4)
        self.btn_confirm.setGeometry(QtCore.QRect(900, 490, 211, 41))
        self.btn_confirm.setObjectName("btn_confirm")
        self.btn_reset = QtWidgets.QPushButton(self.frame1_4)
        self.btn_reset.setGeometry(QtCore.QRect(900, 560, 211, 41))
        self.btn_reset.setObjectName("btn_reset")
        self.lb_ds_img = QtWidgets.QLabel(self.frame1_4)
        self.lb_ds_img.setGeometry(QtCore.QRect(90, 120, 640, 480))
        self.lb_ds_img.setText("")
        self.lb_ds_img.setObjectName("lb_ds_img")
        self.lb_state = QtWidgets.QLabel(self.frame1_4)
        self.lb_state.setGeometry(QtCore.QRect(900, 810, 211, 41))
        self.lb_state.setText("")
        self.lb_state.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_state.setObjectName("lb_state")
        self.btn_quit = QtWidgets.QPushButton(self.frame1_4)
        self.btn_quit.setGeometry(QtCore.QRect(1060, 930, 101, 41))
        self.btn_quit.setObjectName("btn_quit")
        self.pwd_lb = QtWidgets.QLabel(self.frame1_4)
        self.pwd_lb.setGeometry(QtCore.QRect(90, 710, 381, 41))
        self.pwd_lb.setObjectName("pwd_lb")
        self.pwd_confirm_lb = QtWidgets.QLabel(self.frame1_4)
        self.pwd_confirm_lb.setGeometry(QtCore.QRect(90, 820, 381, 41))
        self.pwd_confirm_lb.setObjectName("pwd_confirm_lb")
        self.pwd_le = QtWidgets.QLineEdit(self.frame1_4)
        self.pwd_le.setGeometry(QtCore.QRect(90, 770, 331, 41))
        self.pwd_le.setObjectName("pwd_le")
        self.pwd_confirm_le = QtWidgets.QLineEdit(self.frame1_4)
        self.pwd_confirm_le.setGeometry(QtCore.QRect(90, 880, 331, 41))
        self.pwd_confirm_le.setObjectName("pwd_confirm_le")
        self.btn_pwd_confirm = QtWidgets.QPushButton(self.frame1_4)
        self.btn_pwd_confirm.setGeometry(QtCore.QRect(570, 880, 161, 41))
        self.btn_pwd_confirm.setObjectName("btn_pwd_confirm")
        self.lb_pwd_confirm = QtWidgets.QLabel(self.frame1_4)
        self.lb_pwd_confirm.setGeometry(QtCore.QRect(570, 760, 411, 51))
        self.lb_pwd_confirm.setObjectName("lb_pwd_confirm")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Please sign here"))
        self.btn_confirm.setText(_translate("Dialog", "Confirm"))
        self.btn_reset.setText(_translate("Dialog", "Reset"))
        self.btn_quit.setText(_translate("Dialog", "Quit"))
        self.pwd_lb.setText(_translate("Dialog", "Please enter your password (16 characters): "))
        self.pwd_confirm_lb.setText(_translate("Dialog", "Please confirm your password (16 characters): "))
        self.btn_pwd_confirm.setText(_translate("Dialog", "Confirm"))
        self.lb_pwd_confirm.setText(_translate("Dialog", "TextLabel"))
